// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GenerateQRCode(arg1:main.QRParams):Promise<string>;

export function SaveQRCode(arg1:main.QRParams):Promise<string>;

export function SelectLogoFile():Promise<string>;
