// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateQRCode(arg1) {
  return window['go']['main']['App']['GenerateQRCode'](arg1);
}

export function SaveQRCode(arg1) {
  return window['go']['main']['App']['SaveQRCode'](arg1);
}

export function SelectLogoFile() {
  return window['go']['main']['App']['SelectLogoFile']();
}
